Issue 10
dadolhay/dadolhay-ssg pull request #11
Opened 2022-10-04 01:30 UTC by IvaniGabrovsky

I Added support for configuration file (-c --config).

2022-10-04 13:34 UTC, dadolhay requested changes
Also, please add the `prettier` and `eslint` extensions to your VsCode, some of the formatting you did differs from the code style defined in those configs. If you add those, it should be completely automated to format code in the repo.

2022-10-04 13:34 UTC, dadolhay commented on src/utils/args.js
> +    const {input, output, lang} = require(path.join(PATH_PREFIX, configFile));
- The file pat's location should be relative to the working directory. please try to use `path.resolve(configFile)`

- Requiring a file executes it if it is not a json, but a js file there.
- Please check if the file exists
- Please read the file onto a variable and use JSON.parse instead, that should be safe

2022-10-04 13:34 UTC, dadolhay commented on ssg.js
> -
This way we'll have to manually maintain each parameter here later.

```suggestion
let { parsedParams } = config;
if (parsedParams.config) {
  config = {
    ...config,
    ...parseConfigArgs(config.parsedParams.config).parsedParams
  };
}

/ Verify input is given
if (!config.parsedParams.input) {
  // eslint-disable-next-line no-console
  console.log('Input parameter missing');
  process.exit(1);
}

const { language = 'en-CA', output: outputDirPath = DEFAULT_RESULT_FOLDER } =
  config;
```

This should automatically merge everything together later on

2022-10-05 13:09 UTC, dadolhay requested changes

2022-10-05 13:09 UTC, dadolhay commented on src/utils/args.js
> +    };
```suggestion
    const data = fs.readFileSync(configFile, 'utf8');
    
    return { parsedParams: JSON.parse(data) };
```

2022-10-05 13:09 UTC, dadolhay commented on src/config/default_config.json
> +  "lang": "fr"
```suggestion
  "language": "fr"
```

2022-10-05 13:09 UTC, dadolhay commented on ssg.js
> -
Your solution would require us fo modify this merging code for every new config param introduced. Please use a solution like this instead

```suggestion
let { parsedParams } = config;
if (parsedParams.config) {
  parsedParams = {
    ...parsedParams,
    ...parseConfigArgs(config.parsedParams.config).parsedParams
  };
}
/ Verify input is given
if (!parsedParams.input) {
  // eslint-disable-next-line no-console
  console.log('Input parameter missing');
  process.exit(1);
}
const { language = 'en-CA', output: outputDirPath = DEFAULT_RESULT_FOLDER } =
  parsedParams;
```

2022-10-05 17:08 UTC, IvaniGabrovsky commented on ssg.js
> -
Hi Denes, the following recomendation file is failing when I run with -config. I am getting error:  
No txt files to process

2022-10-05 20:22 UTC, dadolhay commented on ssg.js
> -
If you also change 
`inputPath: config.parsedParams.input,` to `inputPath: parsedParams.input,`
in line `67`, it should work (I tested it)

2022-10-06 00:25 UTC, IvaniGabrovsky commented on ssg.js
> -
I fixed it. Please approve the PR and merge.

2022-10-06 02:20 UTC, IvaniGabrovsky commented
Hi Denise this is fixed in this commit 9a40c3e.

2022-10-06 20:42 UTC, dadolhay approved these changes

2022-10-06 20:42 UTC, merged