Add initial support for Markdown
dadolhay/dadolhay-ssg pull request #7
Opened 2022-09-20 16:10 UTC by Ririio

**file.js**
- I had to change the value on your ".replace" with a variable, this is to allow .md or .txt to be converted without changing too much of your already existing code.
- I also, added an "or" on your if statement to consider files that ends with a .md extension
- Your folder now contains an if statement to ensure that the user returns an empty value that will be use to determine whether the specific file should be generated or not on your "ssg.js" file

**dom.js**
- Replaced your ternary operator with an if statement for your createElement, this is to ensure that it consider headings as a valid type instead of simply 'title' and 'paragraph'

**textParser.js**
- Created an if statement just before returning the block to remove the "#" that comes with the .md files, and to also push all the contents as either an h1, h2 or paragraph

2022-09-20 23:50 UTC, dadolhay requested changes

2022-09-20 23:50 UTC, dadolhay commented on inputs/Sherlock-Holmes-Selected-Stories/README.md
> +# dadolhay-ssg
This file is not needed, it's in the incorrect folder

2022-09-20 23:50 UTC, dadolhay commented on inputs/Sherlock-Holmes-Selected-Stories/package.json
> +{
This is also in the incorrect folder

2022-09-20 23:50 UTC, dadolhay commented on src/utils/file.js
> +const { resolve } = require('path');
"path" is alreadin included in line 1.

in the code you can ise `path.resolve` instead of `resolve`

2022-09-20 23:50 UTC, dadolhay commented on src/utils/file.js
> +  return glob.sync(path.join(inputPath, '/**/*')).map(item => {
I think that you can use `/**/*.{txt,md}` here, and all other code below will become much simpler

2022-09-20 23:50 UTC, dadolhay commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
```suggestion
if (lines[0].match(/^=+$/)) {
  // The next line is wholey composed of "=" characters
  // Drop the next line
  lines.shift();
  // Save the block
  blocks.push({ type: 'h1', content: blockContent });
} else if (lines[0].match(/^-+$/))  {
  // The next line is wholey composed of "-" characters
  // Drop the next line
  lines.shift();
  // Save the block
  blocks.push({ type: 'h2', content: blockContent });
} else {
  blocks.push({ type: 'paragraph', content: blockContent });
}
```

2022-09-20 23:50 UTC, dadolhay commented on ssg.js
> +    //Issue 6: Adding a condition to prevent writing on non markdown or text files
With the above changes to globbing, I don't think that these changes will be required. You'll never get an empty input

2022-09-21 00:10 UTC, Ririio commented on inputs/Sherlock-Holmes-Selected-Stories/README.md
> +# dadolhay-ssg
I was just testing how .md works on a folder.

2022-09-21 00:12 UTC, Ririio commented on inputs/Sherlock-Holmes-Selected-Stories/package.json
> +{
I was testing how a non-valid file will affect the input of a folder. There was a problem with how it handles it so I was using for debugging

2022-09-21 00:12 UTC, Ririio commented on src/utils/file.js
> +const { resolve } = require('path');
I honestly thought it was already there so I didn't remove it, I guess I accidentally wrote it

2022-09-21 00:13 UTC, Ririio commented on src/utils/file.js
> +  return glob.sync(path.join(inputPath, '/**/*')).map(item => {
oh I didn't know that's possible, I'm not familiar with regex so I forgot how it works

2022-09-21 00:16 UTC, Ririio commented on src/utils/file.js
> +  return glob.sync(path.join(inputPath, '/**/*')).map(item => {
Yeah it works perfectly, thanks for that

2022-09-21 00:22 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
Do you mind elaborating on how the "=" sign works for a markdown file?

2022-09-21 00:22 UTC, Ririio commented on ssg.js
> +    //Issue 6: Adding a condition to prevent writing on non markdown or text files
Yeah I noticed that so I removed the condition all together

2022-09-21 00:27 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
Wouldn't the value that will be shifted is the line that you want to pass down? Doesn't the = work as 

Something Something
===============

Wouldn't the first line be removed, and the second will become the next line?

2022-09-21 00:34 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
I'm getting an error when implement the code `Cannot read properties of undefined (reading 'match')` Do you have an idea as to why?

2022-09-21 00:36 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
Actually looking through it now, I just added something on the if condition to check whether "lines[0]" is defined before checking on whether it match "=" or "-"

2022-09-21 00:49 UTC, dadolhay commented on inputs/Sherlock-Holmes-Selected-Stories/README.md
> +# dadolhay-ssg
I see but this md file has a different structure

You can put something together from here
https://en.wikipedia.org/wiki/Markdown

2022-09-21 00:50 UTC, dadolhay commented on inputs/Sherlock-Holmes-Selected-Stories/package.json
> +{
Testing is perfectly fine, but we should not commit files that we are using for testing :)

2022-09-21 00:51 UTC, dadolhay commented on src/utils/file.js
> +  return glob.sync(path.join(inputPath, '/**/*')).map(item => {
Any time!

2022-09-21 00:51 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
Now that I'm using it for my code, it doesn't seem to be doing anything. Did it work for yours?

2022-09-21 00:53 UTC, dadolhay commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
In node 18 you can also use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining):
`lines[0]?.match(...)`

2022-09-21 00:53 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
Looking through it the statement always return null

2022-09-21 00:54 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
![image](https://user-images.githubusercontent.com/32577022/191390466-17f2643f-696e-415c-b7d3-31950b0e3dae.png)

2022-09-21 00:55 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
I have a console.log() above the if statement to check on whether it hits a match at some point but it never does. Never used match so I'm not too sure if I'm missing something

2022-09-21 00:59 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
It's returning this at the .html file
![image](https://user-images.githubusercontent.com/32577022/191390976-167a1569-218e-468e-a775-316ef73dd085.png)

2022-09-21 00:59 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
The one at the bottom are the "#"

2022-09-21 13:26 UTC, dadolhay commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
okay, there are two issues:

First, textParser line 17 "eats up" all the subsequent lines, including the === and --- lines, so that needs to be modified to `while(line[0]?.match(/\w/)) {` ... this will only eat up lines with normal text in it

also, in line 40 and 46 the variable should be `lines[0]` and not `blockContent[0]`

If you fix these, it will work

2022-09-21 13:33 UTC, Ririio commented on src/utils/textParser.js
> +    } else blocks.push({ type: 'paragraph', content: blockContent });
what does the `/\w/` mean if you don't mind me asking? It solves it btw

2022-09-21 13:50 UTC, dadolhay approved these changes

2022-09-21 13:50 UTC, merged